

const actions = {
    GET_POY_TYPES_LIST: `GET_POY_TYPES_LIST`,
    REQUEST_GET_POI_TYPES_LIST: `REQUEST_GET_POI_TYPES_LIST`,
    GET_RADIUS_LIST: `GET_RADIUS_LIST`,
    SET_LOCATIONS: `SET_LOCATIONS`,
    SET_TRUCK_LOCATIONS: `SET_TRUCK_LOCATIONS`,
    REQUEST_GET_RADIUS_LIST: `REQUEST_GET_RADIUS_LIST`,
    REQUEST_GET_LOCATION: `REQUEST_GET_LOCATION`,
    REQUEST_GET_TRUCK_LOCATIONS: `REQUEST_GET_TRUCK_LOCATIONS`,
    REQUEST_SET_LOCATION: `REQUEST_SET_LOCATION`,
    REQUEST_SET_LICENSE_PLATE_SELECTED: `REQUEST_SET_LICENSE_PLATE_SELECTED`,
    REQUEST_SET_POI_TYPE_SELECTED: `REQUEST_SET_POI_TYPE_SELECTED`,
    REQUEST_SET_POI_TYPES_LIST: `REQUEST_SET_POI_TYPES_LIST`,
    REQUEST_SET_RADIUS_SELECTED: `REQUEST_SET_RADIUS_SELECTED`,
    REQUEST_SET_RADIUS_LIST: `REQUEST_SET_RADIUS_LIST`,
    REQUEST_GET_SUGGESTIONS: `REQUEST_GET_SUGGESTIONS`,
    SET_LICENSE_PLATE_SELECTED: `SET_LICENSE_PLATE_SELECTED`,
    SET_MINIMUM_DISTANCE: `SET_MINIMUM_DISTANCE`,
    SET_RADIUS_SELECTED: `SET_RADIUS_SELECTED`,
    SET_RADIUS_LIST: `SET_RADIUS_LIST`,
    SET_POI_TYPE_SELECTED: `SET_POI_TYPE_SELECTED`,
    SET_POI_TYPES_LIST: `SET_POI_TYPES_LIST`,
    SET_SUGGESTIONS:`SET_LOCATIONS`
}
export { actions }