const actions = {
    GET_POY_TYPES_LIST: `GET_POY_TYPES_LIST`,
    REQUEST_GET_LOCATIONS: `REQUEST_GET_LOCATIONS`,
    REQUEST_GET_POI_TYPES_LIST: `REQUEST_GET_POI_TYPES_LIST`,
    REQUEST_RESET_LOCATIONS: `REQUEST_RESET_LOCATIONS`,
    REQUEST_RESET_MINIMUM_DISTACE: `REQUEST_RESET_MINIMUM_DISTACE`,
    REQUEST_RESET_SUGGESTIONS: `REQUEST_RESET_SUGGESTIONS`,
    REQUEST_SET_LICENSE_PLATE_SELECTED: `REQUEST_SET_LICENSE_PLATE_SELECTED`,
    REQUEST_SET_NO_LOCATIONS: `REQUEST_SET_NO_LOCATIONS`,
    REQUEST_SET_POI_TYPE_SELECTED: `REQUEST_SET_POI_TYPE_SELECTED`,
    REQUEST_SET_POI_TYPES_LIST: `REQUEST_SET_POI_TYPES_LIST`,
    REQUEST_SET_RADIUS_SELECTED: `REQUEST_SET_RADIUS_SELECTED`,
    REQUEST_SET_SUGGESTIONS: `REQUEST_SET_SUGGESTIONS`,
    RESET_LOCATIONS: `RESET_LOCATIONS`,
    RESET_MINIMUM_DISTACE: `RESET_MINIMUM_DISTACE`,
    RESET_SUGGESTIONS: `RESET_SUGGESTIONS`,
    SET_LICENSE_PLATE_SELECTED: `SET_LICENSE_PLATE_SELECTED`,
    SET_LOCATIONS: `SET_LOCATIONS`,
    SET_MINIMUM_DISTANCE: `SET_MINIMUM_DISTANCE`,
    SET_NO_LOCATIONS: `SET_NO_LOCATIONS`,
    SET_POI_TYPE_SELECTED: `SET_POI_TYPE_SELECTED`,
    SET_POI_TYPES_LIST: `SET_POI_TYPES_LIST`,
    SET_RADIUS_SELECTED: `SET_RADIUS_SELECTED`,
    SET_SUGGESTIONS:`SET_SUGGESTIONS`
}

const poiTypes = {
    'Restaurants': 'restaurant',
    'Hotels': 'lodging',
    'Gas Stations': 'gas_station'
}

const defaultRadiusMessage = 'Select radius'

const defaultPoiTypeMessage = 'Select POI type'

const radiusDefaultList = ['1000', '2000', '4000', '4500']

const licensePlateDefaultMessage = 'License plate (ex: ABC1234)'

export { 
    actions,
    defaultPoiTypeMessage,
    defaultRadiusMessage,
    licensePlateDefaultMessage, 
    poiTypes, 
    radiusDefaultList 
}